/*
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PersonStandaloneSetup extends PersonStandaloneSetupGenerated {

	def static void doSetup() {
		new PersonStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
